
title: Recipes
email: your-email@example.com
description: >-
  A collection of recipes assembled by Síle.
baseurl: "/recipes" # the subpath of your site, e.g. /blog
url: "https://vulpine.house" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-textile-converter

collections:
  tags:
    output: true
    permalink: tag/:title/
    order:
      - beef.textile
      - chicken.textile
      - pork.textile
      - sausage.textile
      - vegetarian.textile
      - kosher.textile
      - passover.textile
      - main_dish.textile
      - side_dish.textile
      - instant_pot.textile
  recipes:
    output: true
    permalink: recipe/:title/

defaults:
  -
    scope:
      path: ""
      type: tags
    values:
      layout: tag
  -
    scope:
      path: ''
      type: recipes
    values:
      layout: recipe

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
